version: 2
updates:
   # maintain dependencies for github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      target-branch: "development"
    labels:
      - "github actions dependencies"

   # maintain dependencies for composer
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      target-branch: "development"
    labels:
      - "composer dependencies"

    # maintain dependencies for gomod
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "weekly"
      target-branch: "development"
    labels:
      - "gomod dependencies"

    # maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
      target-branch: "development"
    labels:
      - "docker dependencies"
